# -*- coding: utf-8 -*-
"""regex with python for email and bd phone.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XU32Ov52Xg3c1_3J9dymh3YvwDabDnYK
"""

import re

with open("emails&phone.txt","r") as file:
    txt=file.read()

print(txt)



gmail_regex = r'\b[A-Za-z0-9._%+-]+@gmail\.com\b'
bd_mobile_regex = r'\+880\d{10}'

gmailid=re.findall(gmail_regex,txt)
print(gmailid)

bd_mobile=re.findall(bd_mobile_regex,txt)
print(bd_mobile)

with open(r'gmail_ids.txt', 'a') as fw:
  for i in gmailid:
    fw.writelines(i+'\n')

with open(r'bd_mobiles.txt', 'a') as fw:
  for i in bd_mobile:
    fw.writelines(i+'\n')
